In [2]:
import requests
import numpy as np
x = requests.get('https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data')


In [23]:
raw_data=[]
for line in x.text.split('\n'):
    raw_data.append(line.split(','))
for sample in raw_data:
    for i,value in enumerate(sample[0:4]):
        if len(sample) < 1:
            continue
        try:
            sample[i] = float(value)
        except:
            sample[i] = 0.0
print(raw_data[0::50])

[[5.1, 3.5, 1.4, 0.2, 'Iris-setosa'], [7.0, 3.2, 4.7, 1.4, 'Iris-versicolor'], [6.3, 3.3, 6.0, 2.5, 'Iris-virginica'], [0.0]]


In [24]:
for sample in raw_data:
    if len(sample) < 2:
        continue
    if 'setosa' in sample[-1]:
        sample[-1] = 0.0
    elif 'versicolor' in sample[-1]:
        sample[-1] = 1.0
    elif 'virginica' in sample[-1]:
        sample[-1] = 2.0

[[5.1, 3.5, 1.4, 0.2, 0.0], [4.9, 3.0, 1.4, 0.2, 0.0], [4.7, 3.2, 1.3, 0.2, 0.0], [4.6, 3.1, 1.5, 0.2, 0.0], [5.0, 3.6, 1.4, 0.2, 0.0], [5.4, 3.9, 1.7, 0.4, 0.0], [4.6, 3.4, 1.4, 0.3, 0.0], [5.0, 3.4, 1.5, 0.2, 0.0], [4.4, 2.9, 1.4, 0.2, 0.0], [4.9, 3.1, 1.5, 0.1, 0.0], [5.4, 3.7, 1.5, 0.2, 0.0], [4.8, 3.4, 1.6, 0.2, 0.0], [4.8, 3.0, 1.4, 0.1, 0.0], [4.3, 3.0, 1.1, 0.1, 0.0], [5.8, 4.0, 1.2, 0.2, 0.0], [5.7, 4.4, 1.5, 0.4, 0.0], [5.4, 3.9, 1.3, 0.4, 0.0], [5.1, 3.5, 1.4, 0.3, 0.0], [5.7, 3.8, 1.7, 0.3, 0.0], [5.1, 3.8, 1.5, 0.3, 0.0], [5.4, 3.4, 1.7, 0.2, 0.0], [5.1, 3.7, 1.5, 0.4, 0.0], [4.6, 3.6, 1.0, 0.2, 0.0], [5.1, 3.3, 1.7, 0.5, 0.0], [4.8, 3.4, 1.9, 0.2, 0.0], [5.0, 3.0, 1.6, 0.2, 0.0], [5.0, 3.4, 1.6, 0.4, 0.0], [5.2, 3.5, 1.5, 0.2, 0.0], [5.2, 3.4, 1.4, 0.2, 0.0], [4.7, 3.2, 1.6, 0.2, 0.0], [4.8, 3.1, 1.6, 0.2, 0.0], [5.4, 3.4, 1.5, 0.4, 0.0], [5.2, 4.1, 1.5, 0.1, 0.0], [5.5, 4.2, 1.4, 0.2, 0.0], [4.9, 3.1, 1.5, 0.1, 0.0], [5.0, 3.2, 1.2, 0.2, 0.0], [5.5, 3.5, 1.3, 0.2, 0.0], 

In [26]:
raw_data = raw_data[:150]
print(len(raw_data))

150


In [27]:
np_data = np.array(raw_data)
np_data.shape

(150, 5)

### 기본 통계값
* 전체(150샘플) 평균, 표준편차 - sepal length, sepal width, petal length, petal with
* 품종별 평균, 표준편차
* 평균 np.mean()
* 평균 np.std()

In [87]:
print(np.mean(np_data[:,:-1] ,axis = 0), np.std(np_data[:,:-1], axis = 0))
print('setosa 평균: {}'.format(np.mean(np_data[0:50,:-1],axis = 0)),'\tsetosa 표준편차:{}'.format(np.std(np_data[0:50,:-1],axis = 0)),
      '\nversicolor 평균: {}'.format(np.mean(np_data[50:100,:-1], axis = 0)),'\tversicolor 표준편차:{}'.format(np.std(np_data[50:100,:-1],axis = 0)),
      '\nvirginica 평균: {}'.format(np.mean(np_data[100:,:-1],axis = 0)),'\tvirginica 표준편차:{}'.format(np.std(np_data[100:,:-1],axis = 0)))

[5.84333333 3.054      3.75866667 1.19866667] [0.82530129 0.43214658 1.75852918 0.76061262]
setosa 평균: [5.006 3.418 1.464 0.244] 	setosa 표준편차:[0.34894699 0.37719491 0.17176728 0.10613199] 
versicolor 평균: [5.936 2.77  4.26  1.326] 	versicolor 표준편차:[0.51098337 0.31064449 0.46518813 0.19576517] 
virginica 평균: [6.588 2.974 5.552 2.026] 	virginica 표준편차:[0.62948868 0.31925538 0.54634787 0.27188968]


In [82]:
print(np.mean(np_data,axis = 0))
print(np.std(np_data,axis = 0))
print(np.corrcoef(np_data.T))# 상관도

[5.84333333 3.054      3.75866667 1.19866667 1.        ]
[0.82530129 0.43214658 1.75852918 0.76061262 0.81649658]
[[ 1.         -0.10936925  0.87175416  0.81795363  0.78256123]
 [-0.10936925  1.         -0.4205161  -0.35654409 -0.4194462 ]
 [ 0.87175416 -0.4205161   1.          0.9627571   0.94904254]
 [ 0.81795363 -0.35654409  0.9627571   1.          0.95646382]
 [ 0.78256123 -0.4194462   0.94904254  0.95646382  1.        ]]


In [85]:
fiter_setosa = np_data[:,-1] ==0.0
fiter_versicolor = np_data[:,-1] ==1.0
fiter_virginica = np_data[:,-1] ==2.0

print(np.mean(np_data[fiter_setosa],axis = 0))
print(np.std(np_data[fiter_setosa],axis = 0))


[5.006 3.418 1.464 0.244 0.   ]
[0.34894699 0.37719491 0.17176728 0.10613199 0.        ]
